/*
 * ultrasonic.h
 *
 *  Created on: Oct 13, 2021
 *      Author: Mohamed
*/

#include "std_types.h"

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#define TRIGON  PORTB|=(1<<5)
#define TRIGOFF PORTB&=~(1<<5)
/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description :
 * Initialize the ICU driver as required.
 *  Setup the ICU call back function.
Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void);
/*
 * Description :
*Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);
/*Description
* This is the call back function called by the ICU driver.
* This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void);
/*
 * Description :
*Send the trigger pulse by using Ultrasonic_Trigger function.
 *Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);
#endif /* ULTRASONIC_H_ */
